

trigger:
- master

pool:
  vmImage: 'windows-latest'
  name: 'Default'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      workingDirectory: '$(System.DefaultWorkingDirectory)/SandboxProf'
